steps:
# =========================
# STEP 1: BUILD WAR FROM SOURCE
# =========================
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get install -y ant default-jdk
      ant -f build.xml jar

# =========================
# STEP 2: COPY WAR TO VM
# =========================
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - scp
    - dist/StudyWeb.war
    - ubuntu@instance-20260222-144634:~
    - --zone=asia-southeast1-a

# =========================
# STEP 3: DEPLOY & RESTART TOMCAT
# =========================
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - ssh
    - ubuntu@instance-20260222-144634
    - --zone=asia-southeast1-a
    - --
    - |
      sudo systemctl stop tomcat10
      sudo rm -rf /var/lib/tomcat10/webapps/ROOT*
      sudo mv ~/StudyWeb.war /var/lib/tomcat10/webapps/ROOT.war
      sudo systemctl start tomcat10

options:
  logging: CLOUD_LOGGING_ONLY